name: Build and release
on:
  repository_dispatch:
    types: [electron-release]
permissions:
  contents: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./career-assistant
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_cmd: win
          - os: macos-latest
            build_cmd: mac
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v6
        with:
          repository: shunliz/career-assistant
          token: ${{ secrets.MAIN_REPO_TOKEN }}
          ref: ${{ github.event.client-payload.version }}
          path: ./career-assistant
      - uses: actions/setup-node@v6
        with: { node-version: 22 }
      - run: npm ci
      - name: Build
        env:
          BUILD_SCRIPT: ${{ matrix.build_cmd }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: npm run build:$BUILD_SCRIPT
      - uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.os }}
          path: ./career-assistant/dist/**
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with: { path: ./dist }
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client-payload.version }}
          draft: false
          files: |
            dist/**/career-assistant-*.exe
            dist/**/career-assistant-*.dmg
            dist/**/latest-mac.yml
            dist/**/latest-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}